name: beepo
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  intl: ^0.17.0
  hive: any
  url_launcher: ^6.0.12
  share_plus: any
  hive_flutter: any
  http: ^0.13.4
  iconsax: ^0.0.8
  flutter_svg: ^1.0.3
  pin_code_fields: ^7.3.0
  country_picker: ^2.0.12
  hawk_fab_menu: ^1.1.2
  lottie: ^1.3.0
  cached_network_image: ^3.2.0
  image_picker: 0.8.4+4
  image_cropper: ^2.0.3
  local_auth: ^2.1.0
  mqtt_client: 9.4.1
  web_socket_channel: ^2.2.0
  path_provider: any
  #audio_recorder: any
  path: any
  permission_handler: any
  record_mp3: ^2.1.0
  audioplayers: ^0.18.1

  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1

  # Firebase
  # firebase_core: ^1.17.1
  # firebase_auth: ^3.3.19
  # cloud_firestore: ^3.1.17
  # firebase_storage: ^10.2.17
  fluttertoast: ^8.0.9

  # Cryptography
  cryptography:
  cryptography_flutter:
  rsa_encrypt: ^2.0.0
  pointycastle:
  encrypt: ^5.0.1
  convert: ^3.0.2
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2
  firebase_auth_web: ^4.2.2
  firebase_core: ^1.20.0
  provider: ^6.0.5
  firebase_core_platform_interface: 4.5.1
  firebase_storage: ^10.3.11
  just_audio: ^0.9.31

#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.3+1
  flutter_launcher_icons:

flutter_native_splash:
  background_image: "assets/splash.png"
  android: true
  ios: true

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/beepo.png"
  remove_alpha_ios: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 900
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
